export const ALL_MODAL_CLOSE = 'ALL_MODAL_CLOSE'
export const BACKLAYOUT_OPEN = 'BACKLAYOUT_OPEN'
export const BACKLAYOUT_CLOSE = 'BACKLAYOUT_CLOSE'
export const PLACEMARK_EDIT_OPEN = 'PLACEMARK_EDIT_OPEN'
export const PLACEMARK_EDIT_CLOSE = 'PLACEMARK_EDIT_CLOSE'
export const PLACEMARK_FORM_OPEN = 'PLACEMARK_FORM_OPEN'
export const PLACEMARK_FORM_CLOSE = 'PLACEMARK_FORM_CLOSE'

