export const USER_NOTEPADS_LOADING = 'USER_NOTEPADS_LOADING'
export const USER_NOTEPADS_LOAD_SAGA = 'USER_NOTEPADS_LOAD_SAGA'
export const USER_NOTEPADS_LOADED = 'USER_NOTEPADS_LOADED'
export const NOTEPAD_CREATE = 'NOTEPAD_CREATE'
export const NOTEPAD_DELETE = 'NOTEPAD_DELETE'


