export const USER_SET = 'USER_SET'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_CREATE = 'USER_CREATE'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_SET_SAGA = 'USER_SET_SAGA'
export const USER_LOGOUT_SAGA = 'USER_LOGOUT_SAGA'
export const USER_CREATE_SAGA = 'USER_CREATE_SAGA'
export const USER_UPDATE_SAGA = 'USER_UPDATE_SAGA'

